//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApibookingAdministrator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKING
    {
        public int BOOKING_ID { get; set; }
        public Nullable<int> ROOM_ID { get; set; }
        public Nullable<int> RIDER_ID { get; set; }
        public string CODE { get; set; }
        public Nullable<System.DateTime> CHEK_IN { get; set; }
        public Nullable<System.DateTime> CHEK_OUNT { get; set; }
        public Nullable<int> NUMBER_PEOPLE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> STATE_BOOKING_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> STATE { get; set; }
    
        public virtual RIDER RIDER { get; set; }
        public virtual ROOM ROOM { get; set; }
        public virtual STATE_BOOKING STATE_BOOKING { get; set; }
    }
}
