//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApibookingAdministrator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENT_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOCUMENT_TYPE()
        {
            this.RIDER = new HashSet<RIDER>();
        }
    
        public int DOCUMENT_TYPE_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<bool> STATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RIDER> RIDER { get; set; }
    }
}
