//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApibookingAdministrator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROOM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ROOM()
        {
            this.BOOKING = new HashSet<BOOKING>();
            this.ROOM_TAX = new HashSet<ROOM_TAX>();
        }
    
        public int ROOM_ID { get; set; }
        public Nullable<int> HOTEL_ID { get; set; }
        public Nullable<int> NUMBER { get; set; }
        public Nullable<int> FLOOR { get; set; }
        public Nullable<int> CAPACITY { get; set; }
        public Nullable<int> ROOM_TYPE_ID { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> ROOM_STATE_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKING> BOOKING { get; set; }
        public virtual HOTEL HOTEL { get; set; }
        public virtual ROOM_STATE ROOM_STATE { get; set; }
        public virtual ROOM_TYPE ROOM_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ROOM_TAX> ROOM_TAX { get; set; }
    }
}
