//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApibookingAdministrator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROOM_TAX
    {
        public int ROOM_TAX_ID { get; set; }
        public int ROOM_ID { get; set; }
        public int TAX_ID { get; set; }
        public bool STATE { get; set; }
    
        public virtual ROOM ROOM { get; set; }
        public virtual TAX TAX { get; set; }
    }
}
